export enum Skill {
  acrobatics = 'acrobatics',
  animalHandling = 'animalHandling',
  athletics = 'athletics',
  deception = 'deception',
  insight = 'insight',
  investigation = 'investigation',
  intimidation = 'intimidation',
  nature = 'nature',
  perception = 'perception',
  performance = 'performance',
  persuasion = 'persuasion',
  sleightOfHand = 'sleightOfHand',
  stealth = 'stealth',
  survival = 'survival',
}
